### ISSUE TITLE
Can not "parse container string"

### ISSUE THREAD

**Issue by hukai916** [nf-core/atacseq#255] opened 2023-01-09 15:47 UTC
### Description of the bug

This Error message pops out when trying to download Singularity images.

### Command used and terminal output

```console
nf-core download atacseq
```

And select `download singularity image` option.

Output:
```
? Choose compression type: none
INFO     Saving 'nf-core/atacseq'
          Pipeline revision: '2.0'
          Pull containers: 'singularity'
          Output directory: 'nf-core-atacseq-2.0'
INFO     Downloading workflow files from GitHub
INFO     Downloading centralised configs from GitHub
ERROR    Cannot parse container string in
         'nf-core-atacseq-2.0/workflow/modules/nf-core/bowtie2/align/main.nf':

             ${ workflow.containerEngine ==

         ⚠ Skipping this singularity image..
INFO     Found 32 containers
```
```


### Relevant files

_No response_

### System information

_No response_

**Comment by haibol2016** [comment] 2023-03-30 19:16
change the double quotes inside double quotes to single quotes

**Comment by hukai916** [comment] 2023-03-30 19:40
Thx @haibol2016 , can you elaborate on it?

**Comment by haibol2016** [comment] 2023-03-30 20:01
Double quotes can’t be inside double quotes.  For example, “a name “A” is not well delimited”.  Instead, “a name ‘A’ is not well delimited”.      Sent from Mail for Windows From: hukai916Sent: Thursday, March 30, 2023 3:41 PMTo: nf-core/atacseqCc: Haibo Liu; MentionSubject: Re: [nf-core/atacseq] Can not "parse container string" (Issue #255) Thx @haibol2016 , can you elaborate on it?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by hukai916** [comment] 2023-03-30 20:13
Thanks @haibol2016 !

**Comment by li1311139481** [comment] 2023-04-10 11:17
> change https://github.com/nf-core/atacseq/blob/master/modules/nf-core/bowtie2/align/main.nf#L6-L8 to container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ? 'https://depot.galaxyproject.org/singularity/mulled-v2-ac74a7f02cebcfcc07d8e8d1d750af9c83b4d45a:a0ffedb52808e102887f6ce600d092675bf3528a-0' : 'quay.io/biocontainers/mulled-v2-ac74a7f02cebcfcc07d8e8d1d750af9c83b4d45a:a0ffedb52808e102887f6ce600d092675bf3528a-0' }"

hello
Thank you for your reply. 
Do you mean that I can continue to download the image using `nf-core download atacseq -r 2.0 --container singularity`, and only need to manually change the double quotes to single quotes after the download is complete, and then it can be used normally. Right?

**Comment by haibol2016** [comment] 2023-04-10 12:44
Yes, that is correct.

**Comment by JoseEspinosa** [comment] 2023-06-12 13:27
This is fixed in development and the issue is duplicated (see #270). Will then close it.

**Closed by JoseEspinosa** 2023-06-12 13:27 UTC
Labels: bug, duplicate
