### ISSUE TITLE
featureCounts coupled to DESeq2

### ISSUE THREAD

**Issue by julia170** [nf-core/atacseq#76] opened 2020-01-30 18:00 UTC
We run ATAC samples that are not in distinct experimental groups (no replicates) but still would like to make a comparison between the number of reads of each sample in the consensus peaks. However, currently this is not possible because the featureCounts step that does this analysis is coupled to the DESeq2 analysis, which is skipped in the absence of replicates. It would be helpful to separate the two processes, so that the featureCounts step can still be run even if DESeq2 is skipped.

**Comment by drpatelh** [comment] 2020-01-31 17:24
Fixed in https://github.com/nf-core/atacseq/pull/77

**Comment by drpatelh** [comment] 2020-01-31 17:28
@julia170 This should be fixed now. You can test it out by using `-r dev` in the command. That will use the `dev` version of the container and the pipeline. You will have to remove your local copy of the pipeline first:
`rm -rf ~/.nextflow/assets/nf-core/atacseq/`

Note: This wont be fully reproducible until the pipeline is released because changes will most likely be made in the meantime. Be good if you can test it out though 👍

**Closed** 2020-01-31 17:28 UTC
Labels: enhancement
