### ISSUE TITLE
Can't skip trimming

### ISSUE THREAD

**Issue by Phlya** [nf-core/atacseq#78] opened 2020-02-04 12:06 UTC
When I tried to skip trimming I got this error:

```
ERROR ~ No signature of method: java.util.ArrayList.ifEmpty() is applicable for argument types: (ArrayList) values: [[]]
Possible solutions: isEmpty(), isEmpty(), first(), first()

 -- Check script 'main.nf' at line: 1899 or see '.nextflow.log' file for more details
```

**Comment by drpatelh** [comment] 2020-02-04 13:04
Hi @Phyla. Yes, this is bug with the current release. It has been fixed on the `dev` branch of the pipeline which you can run using `-r dev`. 

There was a similar issue with the `chipseq` pipeline:
https://github.com/nf-core/chipseq/issues/118#issuecomment-552008949

Unfortunately, if you use `dev` now then the only downside is that the workflow wont be fully reproducible because the pipeline hasnt been officially released and tagged with static Docker containers.

Ive never tried before but I wonder if it matters whether you perform trimming again :thinking: i.e. in theory you should just trim alot less. Maybe worth giving that a go and looking at the `cutadapt` logs in `results/trim_galore/logs/` to see if that is actually the case.

**Comment by drpatelh** [comment] 2020-02-04 13:04
Closing for now but let me know if you have any more issues :+1:

**Closed by drpatelh** 2020-02-04 13:04 UTC
Labels: bug
