### ISSUE TITLE
Failed to create Conda environment (UnsatisfiableError)

### ISSUE THREAD

**Issue by jma1991** [nf-core/atacseq#64] opened 2019-11-20 17:20 UTC
Nextflow fails to create a conda environment using the environment.yml provided with the pipeline:

```
$ nextflow run nf-core/atacseq -profile test,conda

N E X T F L O W  ~  version 19.10.0
Launching `nf-core/atacseq` [spontaneous_turing] - revision: fa1e3f8993 [master]
----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/atacseq v1.1.0
----------------------------------------------------
Run Name             : spontaneous_turing
Data Type            : Paired-End
Design File          : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/design.csv
Genome               : Not supplied
Fasta File           : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genome.fa
GTF File             : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genes.gtf
Mitochondrial Contig : MT
MACS2 Genome Size    : 1.2E+7
Min Consensus Reps   : 1
MACS2 Narrow Peaks   : No
MACS2 Broad Cutoff   : 0.1
Trim R1              : 0 bp
Trim R2              : 0 bp
Trim 3' R1           : 0 bp
Trim 3' R2           : 0 bp
NextSeq Trim         : 0 bp
Fingerprint Bins     : 100
Save Genome Index    : No
Max Resources        : 6 GB memory, 2 cpus, 12h time per job
Output Dir           : ./results
Launch Dir           : /home/jashmore/fast/kaji/atacseq
Working Dir          : /home/jashmore/fast/kaji/atacseq/work
Script Dir           : /home/jashmore/.nextflow/assets/nf-core/atacseq
User                 : jashmore
Config Profile       : test,conda
Config Description   : Minimal test dataset to check pipeline function
----------------------------------------------------
[-        ] process > CheckDesign -

Error executing process > 'CheckDesign (design.csv)'

Caused by:
  Failed to create Conda environment
  command: conda env create --prefix /home/jashmore/fast/kaji/atacseq/work/conda/nf-core-atacseq-1.1.0-122cbc6d9b1e4b6a246c5040c42e496b --file /home/jashmore/.nextflow/assets/nf-core/atacseq/environment.yml
```
The reason for the failure appears to be a long list of incompatible software:

```
    UnsatisfiableError: The following specifications were found to be incompatible with each other:

    Package libpng conflicts for:
    ucsc-bedgraphtobigwig=377 -> libpng[version='>=1.6.35,<1.7.0a0']
    r-base=3.4.1 -> libpng[version='>=1.6.22,<1.6.31|>=1.6.28,<1.7|>=1.6.32,<1.6.35|>=1.6.34,<1.7.0a0']
    Package libgcc conflicts for:
    homer=4.9.1 -> libgcc
    bedtools=2.27.1 -> libgcc
    bamtools=2.5.1 -> libgcc
    bwa=0.7.17 -> libgcc
    r-base=3.4.1 -> libgcc
    preseq=2.0.3 -> libgcc
    r-reshape2=1.4.3 -> libgcc
    r-lattice=0.20_35 -> libgcc
    Package openssl conflicts for:
    r-base=3.4.1 -> openssl[version='>=1.0.2o,<1.0.3a']
    ucsc-bedgraphtobigwig=377 -> openssl[version='>=1.0.2p,<1.0.3a']
    samtools=1.9 -> openssl[version='>=1.0.2p,<1.0.3a|>=1.0.2r,<1.0.3a|>=1.1.1a,<1.1.2a']
    Package r-locfit conflicts for:
    bioconductor-deseq2=1.20.0 -> r-locfit
    Package curl conflicts for:
    r-base=3.4.1 -> curl[version='>=7.44.0,<8|>=7.59.0,<8.0a0']
    samtools=1.9 -> curl[version='>=7.59.0,<8.0a0|>=7.64.0,<8.0a0']
    pysam=0.15.2 -> curl[version='>=7.59.0,<8.0a0|>=7.64.0,<8.0a0|>=7.64.1,<8.0a0']
    Package r-base conflicts for:
    bioconductor-deseq2=1.20.0 -> r-base[version='>=3.4.1,<3.4.2.0a0|>=3.5.1,<3.5.2.0a0']
    r-reshape2=1.4.3 -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.5,<3.6.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
    r-xfun=0.3 -> r-base[version='>=3.4.1,<3.4.2.0a0|>=3.5.1,<3.5.2.0a0']
    r-rcolorbrewer=1.1_2 -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.5,<3.6.0a0|>=3.5.1,<3.5.2.0a0|>=3.6,<3.7.0a0']
    r-lattice=0.20_35 -> r-base[version='3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5.0,<3.5.1.0a0|>=3.5.1,<3.5.2.0a0']
    bioconductor-vsn=3.46.0 -> r-base=3.4.1
```

**Comment by drpatelh** [comment] 2019-11-21 09:33
Hi @jma1991 ! The same command is working for me locally using `conda v4.6.11` and `Nextflow v19.10.0`. Maybe the version of `conda` you have isnt recent enough?

In any case, I would recommend using either Docker or Singularity if it all possible. With regard to reproducibility Conda is great if you use exactly the same environment for all of your pipeline runs now and in the future. However, in practice this can be quite difficult especially since some of the low-level dependencies in the environment may change if created at a later date. If you use Docker and Singularity you are ensured to be using a static container containing all of the pipeline dependencies. Have a look at the options available to you and we can discuss if you need any more help. If you havent already, maybe also worth joining the `atacseq` channel on the `nf-core` Slack workspace 👍 
https://nf-co.re/join

**Comment by jma1991** [comment] 2019-11-21 13:05
Thank you for replying. Unfortunately, I do not have root permission on the machine I'm using so cannot install Docker or Singularity. I updated conda to v4.7.12 and nextflow to 19.10.0 and now I get a different error:

```
$ nextflow run nf-core/atacseq -profile test,conda
N E X T F L O W  ~  version 19.10.0
Launching `nf-core/atacseq` [jolly_bernard] - revision: fa1e3f8993 [master]
----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/atacseq v1.1.0
----------------------------------------------------
Run Name             : jolly_bernard
Data Type            : Paired-End
Design File          : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/design.csv
Genome               : Not supplied
Fasta File           : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genome.fa
GTF File             : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genes.gtf
Mitochondrial Contig : MT
MACS2 Genome Size    : 1.2E+7
Min Consensus Reps   : 1
MACS2 Narrow Peaks   : No
MACS2 Broad Cutoff   : 0.1
Trim R1              : 0 bp
Trim R2              : 0 bp
Trim 3' R1           : 0 bp
Trim 3' R2           : 0 bp
NextSeq Trim         : 0 bp
Fingerprint Bins     : 100
Save Genome Index    : No
Max Resources        : 6 GB memory, 2 cpus, 12h time per job
Output Dir           : ./results
Launch Dir           : /home/jashmore/fast/kaji/atacseq
Working Dir          : /home/jashmore/fast/kaji/atacseq/work
Script Dir           : /home/jashmore/.nextflow/assets/nf-core/atacseq
User                 : jashmore
Config Profile       : test,conda
Config Description   : Minimal test dataset to check pipeline function
----------------------------------------------------
executor >  local (1)
[65/f742f7] process > CheckDesign (design.csv) [100%] 1 of 1 ✔
groovy.lang.MissingPropertyException: No such property: stackTraceDepth for class: nextflow.dag.MultipleInputChannelException
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
        at nextflow.dag.MultipleInputChannelException.toString(MultipleInputChannelException.groovy)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.io.PrintWriter.println(PrintWriter.java:837)
        at java.base/java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:768)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:725)
        at org.apache.commons.lang.exception.ExceptionUtils.getStackTrace(ExceptionUtils.java:896)
        at nextflow.util.LoggerHelper.findErrorLine(LoggerHelper.groovy:538)
        at nextflow.util.LoggerHelper.appendFormattedMessage(LoggerHelper.groovy:434)
        at nextflow.util.LoggerHelper.fmtEvent(LoggerHelper.groovy:414)
        at nextflow.util.LoggerHelper$CaptureAppender.append(LoggerHelper.groovy:606)
        at nextflow.util.LoggerHelper$CaptureAppender.append(LoggerHelper.groovy)
        at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.error(Logger.java:538)
        at nextflow.cli.Launcher.run(Launcher.groovy:505)
        at nextflow.cli.Launcher.main(Launcher.groovy:639)
```

It appears to be a Java-related error now? I am using JDK 11.0.5

**Comment by drpatelh** [comment] 2019-11-22 04:13
So you are now able to create the Conda environment successfully and the pipeline fails at the first process?

Don't know why you are getting the error above. I think the minimum required version is Java 8. @pditommaso Any ideas?

**Comment by pditommaso** [comment] 2019-11-22 09:57
That error stack trace looks bad! could you please report it as an issue on the GH project?

**Comment by jma1991** [comment] 2019-11-22 11:21
I have filed an issue here: https://github.com/nextflow-io/nextflow/issues/1387#issue-527139175

Thank you both!

**Comment by drpatelh** [comment] 2019-11-22 11:48
Thanks @jma1991 @pditommaso  :+1: I'll close this in favour of the issue you created on the Nextflow repo. Please feel free to reopen if required.

**Closed** 2019-11-22 11:49 UTC
Labels: help wanted
