### ISSUE TITLE
How to define script dir when running with conda

### ISSUE THREAD

**Issue by mavershang** [nf-core/atacseq#106] opened 2020-06-11 15:47 UTC
Hi there, I was trying to run this pipeline using conda with LSF, but failed with error "can't find command markdown_tohtml.r" (detail error msg as below). So I just wandering how could I define the script dir?

Error msg:
```
[0;35m[nf-core/atacseq] Pipeline completed with errors
WARN: Killing pending tasks (4)
Error executing process > 'output_documentation'                                                                                              

Caused by:                                                                                                                                    
  Process `output_documentation` terminated with an error exit status (127)                                                                   

Command executed:                                                                                                                             

  markdown_to_html.r output.md results_description.html                                                                                       

Command exit status:                                                                                                                          
  127                                                                                                                                         

Command output:                                                                                                                               
  (empty)                                                                                                                                     

Command error:
  .command.sh: line 2: markdown_to_html.r: command not found

Work dir:
  /hpc/grid/wip_drm_targetsciences/users/shangl02/Software/Nextflow/atacSeq_workDir/work/df/e1d8bb4c8ca4a63d4fca0967a89e5a

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

```

Nextflow.config
```
/*
 * -------------------------------------------------
 *  nf-core/atacseq Nextflow config file
 * -------------------------------------------------
 * Default config options for all environments.
 */

// Global default params, used in configs
params {

  // Options: Generic
  single_end = false
  seq_center = false
  fragment_size = 0
  fingerprint_bins = 500000

  // Options: References
  genome = false
  tss_bed = false
  save_reference = false

  // Options: Trimming
  clip_r1 = 0
  clip_r2 = 0
  three_prime_clip_r1 = 0
  three_prime_clip_r2 = 0
  trim_nextseq = 0
  skip_trimming = false
  save_trimmed = false

  // Options: Alignments
  keep_mito = false
  keep_dups = false
  keep_multi_map = false
  skip_merge_replicates = false
  save_align_intermeds = false

  // Options: Peaks
  narrow_peak = false
  broad_cutoff = 0.1
  min_reps_consensus = 1
  save_macs_pileup = false
  skip_diff_analysis = false

  // Options: QC
  skip_fastqc = false
  skip_picard_metrics = false
  skip_preseq = false
  skip_plot_profile = false
  skip_plot_fingerprint = false
  skip_ataqv = false
  skip_igv = false
  skip_multiqc = false

  // Options: AWSBatch
  awsqueue = false
  awsregion = 'eu-west-1'

  // Options: Config
  multiqc_config = "$baseDir/assets/multiqc/multiqc_config.yaml"
  bamtools_filter_pe_config = "$baseDir/assets/bamtools_filter_pe.json"
  bamtools_filter_se_config = "$baseDir/assets/bamtools_filter_se.json"

  // Options: Custom config
  custom_config_version = 'master'
  custom_config_base = "https://raw.githubusercontent.com/nf-core/configs/${params.custom_config_version}"
  config_profile_description = false
  config_profile_contact = false
  config_profile_url = false

  // Options: Other
  help = false
  outdir = './results'
  igenomes_base = 's3://ngi-igenomes/igenomes/'
  igenomes_ignore = false
  max_multiqc_email_size = 25.MB
  tracedir = "${params.outdir}/pipeline_info"
  email = false
  email_on_fail = false
  plaintext_email = false
  monochrome_logs = false
  name = false
  hostnames = false
  clusterOptions = false

  // Defaults only, expecting to be overwritten
  max_memory = 128.GB
  max_cpus = 16
  max_time = 240.h

}

// Container slug. Stable releases should specify release tag!
// Developmental code should specify :dev
process.container = 'nfcore/atacseq:1.1.0'

// Load base.config by default for all pipelines
includeConfig 'conf/base.config'

// Load nf-core custom profiles from different Institutions
try {
  includeConfig "${params.custom_config_base}/nfcore_custom.config"
} catch (Exception e) {
  System.err.println("WARNING: Could not load nf-core/config profiles: ${params.custom_config_base}/nfcore_custom.config")
}

profiles {
  awsbatch { includeConfig 'conf/awsbatch.config' }
  conda { process.conda = "$baseDir/environment.yml" }
  debug { process.beforeScript = 'echo $HOSTNAME' }
  docker { docker.enabled = true }
  singularity { singularity.enabled = true
                singularity.autoMounts = true }
  test { includeConfig 'conf/test.config' }
}

// Avoid this error:
// WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
// Testing this in nf-core after discussion here https://github.com/nf-core/tools/pull/351, once this is established and works well, nextflow might implement this behavior as new default.
docker.runOptions = '-u \$(id -u):\$(id -g)'

// Load igenomes.config if required
if (!params.igenomes_ignore) {
  includeConfig 'conf/igenomes.config'
}

// Increase time available to build conda environment
conda { 
  createTimeout = "60 min" 
  //cacheDir = '/hpc/grid/wip_drm_targetsciences/users/shangl02/Software/Nextflow/atacSeq_workDir/work/conda'
}

// Export this variable to prevent local Python libraries from conflicting with those in the container
env {
  PYTHONNOUSERSITE = 1
}

// Capture exit codes from upstream processes when piping
process.shell = ['/bin/bash', '-euo', 'pipefail']

timeline {
  enabled = true
  file = "${params.tracedir}/execution_timeline.html"
}
report {
  enabled = true
  file = "${params.tracedir}/execution_report.html"
}
trace {
  enabled = true
  file = "${params.tracedir}/execution_trace.txt"
}
dag {
  enabled = true
  file = "${params.tracedir}/pipeline_dag.svg"
}

manifest {
  name = 'nf-core/atacseq'
  author = 'Harshil Patel'
  homePage = 'https://github.com/nf-core/atacseq'
  description = 'ATACSeq peak-calling and differential analysis pipeline.'
  mainScript = 'main.nf'
  nextflowVersion = '>=19.10.0'
  version = '1.1.0'
}

process {
  executor = 'lsf'
  queue = 'medium'
}


// Function to ensure that resource requirements don't go beyond
// a maximum limit
def check_max(obj, type) {
  if (type == 'memory') {
    try {
      if (obj.compareTo(params.max_memory as nextflow.util.MemoryUnit) == 1)
        return params.max_memory as nextflow.util.MemoryUnit
      else
        return obj
    } catch (all) {
      println "   ### ERROR ###   Max memory '${params.max_memory}' is not valid! Using default value: $obj"
      return obj
    }
  } else if (type == 'time') {
    try {
      if (obj.compareTo(params.max_time as nextflow.util.Duration) == 1)
        return params.max_time as nextflow.util.Duration
      else
        return obj
    } catch (all) {
      println "   ### ERROR ###   Max time '${params.max_time}' is not valid! Using default value: $obj"
      return obj
    }
  } else if (type == 'cpus') {
    try {
      return Math.min( obj, params.max_cpus as int )
    } catch (all) {
      println "   ### ERROR ###   Max cpus '${params.max_cpus}' is not valid! Using default value: $obj"
      return obj
    }
  }
}
```

**Comment by drpatelh** [comment] 2020-06-11 21:33
Hi @mavershang! Can you send me the full command you are using please? Also, you shouldn't need to edit the `nextflow.config` file that is shipped with the pipeline. Its best to create your own custom config with infrastructure settings/parameters you wish to change e.g. you can put the settings below in a file called `custom.config` and pass that to the pipeline using `-c custom.config`.

```nextflow
process {
  executor = 'lsf'
  queue = 'medium'
}
```

The `markdown_to_html.r` file is in the `bin/` directory of the pipeline and should be found automatically because NF exports that directory to `$PATH` by default. You shouldnt have to specify any directories.

Also, I would recommend trying to run the pipeline with either Docker/Singularity if you have the option because using Conda isnt entirely reproducible because the low-level pipeline dependencies can change over time.

**Comment by mavershang** [comment] 2020-06-12 00:02
Thank you @drpatelh . I tried singularity which pops error "unable to write, read-only system". (detail error msg attached as below)

I figured it out: some nodes on our HPC does not have access to the home dir. 

```

Error executing process > 'MergedLibBigWig (ALDH_Low_Erl_OCSA_R1)'                                                                            

Caused by:                                                                                                                                    
  Process `MergedLibBigWig (ALDH_Low_Erl_OCSA_R1)` terminated with an error exit status (2)                                                   

Command executed:                                                                                                                             

  SCALE_FACTOR=$(grep 'mapped (' ALDH_Low_Erl_OCSA_R1.mLb.clN.sorted.bam.flagstat | awk '{print 1000000/$1}')                                 
  echo $SCALE_FACTOR > ALDH_Low_Erl_OCSA_R1.mLb.clN.scale_factor.txt                                                                          
  genomeCoverageBed -ibam ALDH_Low_Erl_OCSA_R1.mLb.clN.sorted.bam -bg -scale $SCALE_FACTOR -pc  | sort -k1,1 -k2,2n >  ALDH_Low_Erl_OCSA_R1.mLb.clN.bedGraph                                                                                                                                
                                                                                                                                              
  bedGraphToBigWig ALDH_Low_Erl_OCSA_R1.mLb.clN.bedGraph genome.fa.sizes ALDH_Low_Erl_OCSA_R1.mLb.clN.bigWig                                  
                                                                                                                                              
  find * -type f -name "*.bigWig" -exec echo -e "bwa/mergedLibrary/bigwig/"{}"\t0,0,178" \; > ALDH_Low_Erl_OCSA_R1.mLb.clN.bigWig.igv.txt     

Command exit status:                                                                                                                          
  2                                                                                                                                           

Command output:                                                                                                                               
  (empty)                                                                                                                                     

Command error:                                                                                                                                
  sort: cannot create temporary file in '': Read-only file system                                                                             

Work dir:                                                                                                                                     
  /hpc/grid/wip_drm_targetsciences/users/shangl02/Software/Nextflow/atacSeq_workDir/work/3a/7585c8a47d6f0ef35106c0962b7734                    

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

**Comment by drpatelh** [comment] 2020-06-12 09:26
Hi @mavershang .This one should be easier to solve and will be fixed in the next release. For now, please see [this comment](https://github.com/nf-core/chipseq/issues/123#issuecomment-556534176). Closing this issue for now but if you have any more problems feel free to reopen or join the #atacseq channel on the [nf-core Slack workspace](https://nf-co.re/join). :slightly_smiling_face:

**Closed** 2020-06-12 09:26 UTC
Labels: question

**Comment by mavershang** [comment] 2020-06-12 14:43
Thank you @denis-yuen . That solved the issue
